spring:
  mail:
    host: ${EMAIL_HOST}
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    port: 587

  application:
    name: royal-grace-cards
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9091
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

stripe:
  api-key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

payment:
  zelle:
    email: payments@royalgracecards.com
  cashapp:
    handle: $RoyalGraceCards

cors:
  allowed:
    origins: ${CORS_ORIGINS:http://localhost:3000,https://*.vercel.app,https://www.royalgracecards.com,https://royalgracecards.com}

logging:
  level:
    root: ${DEBUG_LEVEL}

